# Generated by Django 3.0.5 on 2022-04-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=39)),
                ('email', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
