# Generated by Django 3.0.5 on 2022-04-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rajashtan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('hotels', models.CharField(max_length=100)),
                ('cafes', models.CharField(max_length=100)),
            ],
        ),
    ]
