# Generated by Django 3.0.5 on 2022-04-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajashtan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rajashtan',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='rajashtan/'),
        ),
    ]
