# Generated by Django 3.0.5 on 2022-04-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panjab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panjab',
            name='cafes',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='panjab',
            name='hotels',
            field=models.CharField(max_length=1200),
        ),
    ]
