# Generated by Django 3.0.5 on 2022-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andaman_and_nicobar_island', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andaman_and_nicobar_island',
            name='cafes',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='andaman_and_nicobar_island',
            name='hotels',
            field=models.CharField(max_length=500),
        ),
    ]
