# Generated by Django 3.0.5 on 2022-04-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andaman_and_nicobar_island', '0002_auto_20220419_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andaman_and_nicobar_island',
            name='cafes',
            field=models.CharField(max_length=5004),
        ),
        migrations.AlterField(
            model_name='andaman_and_nicobar_island',
            name='hotels',
            field=models.CharField(max_length=4500),
        ),
    ]
