# Generated by Django 3.0.5 on 2022-04-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telengana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telengana',
            name='cafes',
            field=models.CharField(max_length=13200),
        ),
        migrations.AlterField(
            model_name='telengana',
            name='hotels',
            field=models.CharField(max_length=13200),
        ),
    ]
