# Generated by Django 3.0.5 on 2022-04-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andhra_pradesh', '0002_auto_20220419_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andhra_pradesh',
            name='cafes',
            field=models.CharField(max_length=5050),
        ),
        migrations.AlterField(
            model_name='andhra_pradesh',
            name='hotels',
            field=models.CharField(max_length=5500),
        ),
    ]
