# Generated by Django 3.0.5 on 2022-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattisgarh', '0002_auto_20220419_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattisgarh',
            name='cafes',
            field=models.CharField(max_length=5040),
        ),
        migrations.AlterField(
            model_name='chattisgarh',
            name='hotels',
            field=models.CharField(max_length=5040),
        ),
    ]
