# Generated by Django 3.0.5 on 2022-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assam', '0002_auto_20220419_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assam',
            name='cafes',
            field=models.CharField(max_length=5300),
        ),
        migrations.AlterField(
            model_name='assam',
            name='hotels',
            field=models.CharField(max_length=5300),
        ),
    ]
